* This is an examples intusoft spice options file (isspice_options.inc).
* 
* SiAuditor generates ISspice decks with a set of default options.
* Occasionally, it may be necessary to extend these options in order for ISspice4
* to simulate properly. The default options can be extended by options that
* are contained in the file isspice_options.inc.

* The following options line is the default.

*.options Itl1=500 
*.options Itl4=500
*.options ICSTEP=40
*.options autotol=2
*.options ACCT

